- name: Create a Compute Engine instance
  hosts: localhost
  tasks:
  - name: Create a instance
    gcp_compute_instance:
      name: instance-jenkins
      machine_type: e2-standard-2
      # Refer to https://cloud.google.com/compute/docs/images/os-details#ubuntu_lts
      # or use the command `gcloud compute images list --project=ubuntu-os-cloud`
      zone: asia-southeast1-a
      project: iee-project-2025
      # The service account is needed to create the resources
      auth_kind: serviceaccount 
      service_account_file: ../secrets/iee-project-2025-2305f145d9ec.json
      disks:
        - auto_delete: true
          boot: true
          initialize_params:
            source_image: projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20230727
            disk_size_gb: 30
      # We use the default network with an external IP for SSH
      network_interfaces:
        - network:
            selfLink: global/networks/default
          access_configs:
          - name: External NAT
            type: ONE_TO_ONE_NAT
      state: present # change to absent to delete the instance

  - name: Create inbound firewall rule for port 8081, 30000
    gcp_compute_firewall:
      name: allow-port-8081-50000
      network:
        selfLink: global/networks/default
      allowed:
        - ip_protocol: TCP
          ports:
            - 8081
            - 50000
      source_ranges:
        - 0.0.0.0/0  # Allow traffic from any source (use a more specific source range for security)
      direction: INGRESS # Direction from outside to inside, EGRESS is the opposite direction
      description: Allow incoming traffic on port 8081, 50000
      project: iee-project-2025
      auth_kind: serviceaccount
      service_account_file: ../secrets/iee-project-2025-2305f145d9ec.json
      state: present # change to absent to delete the instance
